# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentStub:
    """Synchronous agent-decision entrypoint, mirrored by the alert.received ->
    alert.decided Kafka path. See docs/ARCHITECTURE.md §3/§4/§5.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAgent = channel.unary_unary(
                '/agent.Agent/RunAgent',
                request_serializer=agent__pb2.RunAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.RunAgentResponse.FromString,
                _registered_method=True)


class AgentServicer:
    """Synchronous agent-decision entrypoint, mirrored by the alert.received ->
    alert.decided Kafka path. See docs/ARCHITECTURE.md §3/§4/§5.
    """

    def RunAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAgent,
                    request_deserializer=agent__pb2.RunAgentRequest.FromString,
                    response_serializer=agent__pb2.RunAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.Agent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Agent:
    """Synchronous agent-decision entrypoint, mirrored by the alert.received ->
    alert.decided Kafka path. See docs/ARCHITECTURE.md §3/§4/§5.
    """

    @staticmethod
    def RunAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.Agent/RunAgent',
            agent__pb2.RunAgentRequest.SerializeToString,
            agent__pb2.RunAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
