# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import memory_store_pb2 as memory__store__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryStoreStub:
    """Historical/contextual data for a single alert key, used by the
    orchestrator's agent to ground its decision. See docs/ARCHITECTURE.md §3/§4/§6.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContext = channel.unary_unary(
                '/memorystore.MemoryStore/GetContext',
                request_serializer=memory__store__pb2.GetContextRequest.SerializeToString,
                response_deserializer=memory__store__pb2.GetContextResponse.FromString,
                _registered_method=True)


class MemoryStoreServicer:
    """Historical/contextual data for a single alert key, used by the
    orchestrator's agent to ground its decision. See docs/ARCHITECTURE.md §3/§4/§6.
    """

    def GetContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=memory__store__pb2.GetContextRequest.FromString,
                    response_serializer=memory__store__pb2.GetContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memorystore.MemoryStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memorystore.MemoryStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryStore:
    """Historical/contextual data for a single alert key, used by the
    orchestrator's agent to ground its decision. See docs/ARCHITECTURE.md §3/§4/§6.
    """

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memorystore.MemoryStore/GetContext',
            memory__store__pb2.GetContextRequest.SerializeToString,
            memory__store__pb2.GetContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
